"""Phase 1 schema.

Creates the five tables that back the EDGAR watcher, financial-fact ingestion,
the poll log used by ``/health``, and the Postgres-backed daily LLM spend
counter. The schema is hand-written rather than autogenerated so that the
indexes and check constraints are visible in one place for review.

Revision ID: 0001_phase1_schema
Revises:
Create Date: 2026-05-15 19:33:00+00:00
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_phase1_schema"
down_revision: str | None = None
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    """Create the Phase 1 tables, constraints, and indexes."""
    op.create_table(
        "filings",
        sa.Column("accession_number", sa.String(length=32), primary_key=True),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("form", sa.String(length=8), nullable=False),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("report_period_end", sa.Date(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'detected'"),
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "form IN ('10-K', '10-Q', '8-K')", name="filings_form_supported"
        ),
        sa.CheckConstraint(
            "status IN ('detected', 'processing', 'processed', 'failed')",
            name="filings_status_valid",
        ),
    )
    op.create_index("ix_filings_cik_filed_at", "filings", ["cik", "filed_at"])
    op.create_index("ix_filings_ticker_filed_at", "filings", ["ticker", "filed_at"])

    op.create_table(
        "financial_facts",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
        ),
        sa.Column(
            "filing_accession",
            sa.String(length=32),
            sa.ForeignKey("filings.accession_number", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("taxonomy", sa.String(length=32), nullable=False),
        sa.Column("concept", sa.String(length=128), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(28, 6), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_period", sa.String(length=8), nullable=True),
        sa.Column("form", sa.String(length=8), nullable=True),
        sa.Column("filed", sa.Date(), nullable=True),
        sa.Column("frame", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "filing_accession",
            "concept",
            "period_end",
            "period_start",
            "unit",
            name="uq_financial_facts_filing_concept_period_unit",
        ),
        sa.CheckConstraint(
            "period_type IN ('instant', 'duration')",
            name="financial_facts_period_type_valid",
        ),
    )
    op.create_index(
        "ix_financial_facts_cik_concept", "financial_facts", ["cik", "concept"]
    )

    op.create_table(
        "watchlist",
        sa.Column("ticker", sa.String(length=16), primary_key=True),
        sa.Column("cik", sa.String(length=10), nullable=False, unique=True),
        sa.Column("company_name", sa.Text(), nullable=False),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "edgar_poll_log",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
        ),
        sa.Column(
            "polled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("tickers_checked", sa.Integer(), nullable=False),
        sa.Column(
            "filings_found",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ok', 'error')", name="edgar_poll_log_status_valid"
        ),
    )
    op.create_index("ix_edgar_poll_log_polled_at", "edgar_poll_log", ["polled_at"])

    op.create_table(
        "daily_llm_spend",
        sa.Column("day", sa.Date(), primary_key=True),
        sa.Column(
            "spent_usd",
            sa.Numeric(18, 6),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )


def downgrade() -> None:
    """Drop every Phase 1 table in reverse order."""
    op.drop_table("daily_llm_spend")
    op.drop_index("ix_edgar_poll_log_polled_at", table_name="edgar_poll_log")
    op.drop_table("edgar_poll_log")
    op.drop_table("watchlist")
    op.drop_index("ix_financial_facts_cik_concept", table_name="financial_facts")
    op.drop_table("financial_facts")
    op.drop_index("ix_filings_ticker_filed_at", table_name="filings")
    op.drop_index("ix_filings_cik_filed_at", table_name="filings")
    op.drop_table("filings")
